Revert "base-files: Define JAVA_HOME by default"
This reverts commit ada652564f09756a81f54495cbc2091125239625.

When enable multilib on a 64-bit system, probably both base-file and
lib32-base-files are installed.
Then both packages want to modify the file "profile", there will be
an error like:
"
Error: Transaction check error:
file /etc/profile conflicts between attempted installs of
lib32-base-files-3.0.14-r148.gpb_virt and
base-files-3.0.14-r148.gpb_virt
"

The task can be added by adding a file to ${sysconfdir}/profile.d/.

Signed-off-by: Fang Jia <fang.jia@windriver.com>
Signed-off-by: Richard Leitner <richard.leitner@skidata.com>