openjdk-build-helper: fix arm64 build
When trying to build for an arm64 machine, such as qemuarm64, parsing of
the recipes fails with the following messages:

WARNING: /meta-java/recipes-core/openjdk/openjdk-7_99b00-2.6.5.bb: Exception during build_dependencies for LLVM_CONFIGURE_ARCH
WARNING: /meta-java/recipes-core/openjdk/openjdk-7_99b00-2.6.5.bb: Error during finalise of /meta-java/recipes-core/openjdk/openjdk-7_99b00-2.6.5.bb
ERROR: ExpansionError during parsing /meta-java/recipes-core/openjdk/openjdk-7_99b00-2.6.5.bb
Traceback (most recent call last):
  File "Var <LLVM_CONFIGURE_ARCH>", line 1, in <module>
  File "/meta-java/classes/openjdk-build-helper.bbclass", line 86, in openjdk_build_helper_get_llvm_configure_arch(d=<bb.data_smart.DataSmart object at 0x7f08fed017c0>):
         else:
    >        if 'shark' in d.getVar('PACKAGECONFIG').split():
                 bb.warn("%s does not support %s in Shark builds yet" % (d.getVar('PN'), arch) );
bb.data_smart.ExpansionError: Failure expanding variable LLVM_CONFIGURE_ARCH, expression was ${@openjdk_build_helper_get_llvm_configure_arch(d)} which triggered exception AttributeError: 'NoneType' object has no attribute 'split'

Using 'bb.utils.contains' solves the problem.

Signed-off-by: Jerome Brunet <jbrunet@baylibre.com>
Signed-off-by: Richard Leitner <richard.leitner@skidata.com>