openjdk-8-cross.inc: fix a libpng build issue
JDK/JRE fails to build for ARM NEON machines, due to a undefined symbol
in libpng, as follows:
| build/jdk/objs/libsplashscreen/pngrutil.o: In function `png_init_filter_functions':
| jdk/src/share/native/sun/awt/libpng/pngrutil.c:4002: undefined reference to `png_init_filter_functions_neon'

This is a known issue already fixed in openjdk upstream, back-port the fix.

Signed-off-by: Ming Liu <peter.x.liu@external.atlascopco.com>
Signed-off-by: Maxin B. John <maxin.john@intel.com>