cacao-native: fix configure RSS regression
Add virtual/java-initial-native and classpath-initial-native
to DEPENDS_class-native

Recipe Specific Sysroots uncovered the following chain:
* ecj-initial fails because java-initial is command not found
* java-initial core dumps:
      "java/lang/NoClassDefFoundError: java/lang/Object"
* strace shows missing .../usr/share/classpath-initial/glibj.zip

Signed-off-by: Tim Orling <timothy.t.orling@linux.intel.com>
Signed-off-by: Maxin B. John <maxin.john@intel.com>